on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Cleanup dist folder
        run: rm -rf dist

      - name: Fetch Tags
        run: git fetch --tags --depth=1

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
